# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-29 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='exif_aperture',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='exif_camera',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='exif_date_taken',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='exif_exposure',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='exif_focal_length',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='exif_iso',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='exif_lens',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='No title', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
