# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-12 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0051_workshop_max_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('see_all_users', 'Can see all users'), ('export_workshop_registration', 'Can download workshop registration data')]},
        ),
    ]
