# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-12 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0051_workshop_max_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='status',
            field=models.CharField(blank=True, choices=[('Z', 'Zaakceptowane'), ('O', 'Odrzucone'), ('X', 'Odwołane')], default=None, max_length=10, null=True),
        ),
    ]
