# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-13 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0053_auto_20190713_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='meeting_point',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
