# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-13 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0054_auto_20190713_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
