# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-19 18:51
from __future__ import unicode_literals

from django.db import migrations
import wwwapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0055_userinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='pesel',
            field=wwwapp.models.PESELField(blank=True, default='', max_length=11),
        ),
    ]
