# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-25 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0056_auto_20190719_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceYearPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=50)),
                ('access_url', models.URLField(blank=True, help_text='URL dla przycisku w menu. Przycisk nie jest wyświetlany jeśli url jest pusty')),
                ('root_path', models.CharField(help_text='bez "/" na końcu i na początku. np. "internety/www15"', max_length=256)),
                ('year', models.IntegerField()),
            ],
            options={
                'ordering': ['year', 'display_name'],
                'permissions': [('access_all_resources', 'Access all resources')],
            },
        ),
    ]
