# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-02-11 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0057_resourceyearpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceyearpermission',
            name='root_path',
            field=models.CharField(help_text='bez "/" na końcu. np. "/internety/www15"', max_length=256),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='lecturer',
            field=models.ManyToManyField(blank=True, related_name='lecturer_workshops', to='wwwapp.UserProfile'),
        ),
    ]
