# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-01 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0058_auto_20200211_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='owncloud_password',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='owncloud_user',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
