# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-08 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def check_orphaned_userinfo(apps, schema_editor):
    UserProfile = apps.get_model("wwwapp", "UserProfile")
    UserInfo = apps.get_model("wwwapp", "UserInfo")
    db_alias = schema_editor.connection.alias

    for user_info in UserInfo.objects.using(db_alias).all():
        if not UserProfile.objects.using(db_alias).filter(user_info__pk=user_info.pk).exists():
            raise Exception(
                'Orphaned UserInfo object found (pk=%d). Please verify and remove it manually first.' % user_info.pk)


def forwards_func(apps, schema_editor):
    UserProfile = apps.get_model("wwwapp", "UserProfile")
    UserInfo = apps.get_model("wwwapp", "UserInfo")
    db_alias = schema_editor.connection.alias

    for user_profile in UserProfile.objects.using(db_alias).all():
        user_profile.user_info.user_profile = user_profile
        user_profile.user_info.save()


def reverse_func(apps, schema_editor):
    UserProfile = apps.get_model("wwwapp", "UserProfile")
    UserInfo = apps.get_model("wwwapp", "UserInfo")
    db_alias = schema_editor.connection.alias

    for user_info in UserInfo.objects.using(db_alias).all():
        user_info.user_profile.user_info = user_info
        user_info.user_profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0060_auto_20200702_1629'),
    ]

    operations = [
        migrations.RunPython(check_orphaned_userinfo, migrations.RunPython.noop),
        migrations.AddField(
            model_name='userinfo',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wwwapp.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wwwapp.UserInfo'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_info',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_profile',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='wwwapp.UserProfile'),
        ),
    ]
